plugins { id 'com.android.application' }
android {
    namespace 'com.e9.resolutetimer'
    compileSdk 35
    defaultConfig { applicationId 'com.e9.resolutetimer'; minSdk 26; targetSdk 35; versionCode 320; versionName '3.20' }
    compileOptions { sourceCompatibility JavaVersion.VERSION_1_8; targetCompatibility JavaVersion.VERSION_1_8 }
}
