package com.personal.lacrossetimer;
import android.app.*;
import android.media.AudioManager;
import android.media.ToneGenerator;
import android.os.*;
import android.content.*;
import android.net.Uri;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.view.*;
import android.widget.*;
import android.text.*;
import java.util.Locale;

public class MainActivity extends Activity {
 int periods=4,minutes=8,period=1; long remain=480000,last; boolean running=false,rp=false,penaltyStarted=false;
 long[] penalty=new long[4]; boolean[] active=new boolean[4]; boolean[] penaltyArmed=new boolean[4];
 TextView game,periodLabel,status,mode,preview; TextView[] pClock=new TextView[4],pState=new TextView[4];
 Button start,prev,next,allPenalties; Switch toggle; EditText team1,team2,score1,score2,phone;
 Button[] periodChoices=new Button[5],minuteChoices=new Button[4];
 int green=Color.rgb(17,126,105),muted=Color.rgb(96,108,119); SharedPreferences prefs;
 android.media.MediaPlayer horn; ToneGenerator tones; boolean audible=false; long finishSoundUntil=0; int soundGeneration=0;
 Handler handler=new Handler(Looper.getMainLooper());
 Runnable pulse=new Runnable(){public void run(){advance();render();handler.postDelayed(this,100);}};
 int dp(float n){return (int)(n*getResources().getDisplayMetrics().density+.5f);}
 @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);prefs=getSharedPreferences("timer",0);restore();advance();build();render();}
 void restore(){periods=prefs.getInt("periods",4);minutes=prefs.getInt("minutes",8);period=prefs.getInt("period",1);remain=prefs.getLong("remain",480000);running=prefs.getBoolean("running",false);rp=prefs.getBoolean("rp",false);penaltyStarted=prefs.getBoolean("penaltyStarted",false);last=prefs.getLong("last",System.currentTimeMillis());for(int i=0;i<4;i++){penalty[i]=prefs.getLong("p"+i,0);active[i]=prefs.getBoolean("a"+i,false);penaltyArmed[i]=prefs.getBoolean("armed"+i,false);}}
 void save(){SharedPreferences.Editor e=prefs.edit().putInt("periods",periods).putInt("minutes",minutes).putInt("period",period).putLong("remain",remain).putBoolean("running",running).putBoolean("rp",rp).putBoolean("penaltyStarted",penaltyStarted).putLong("last",last);for(int i=0;i<4;i++)e.putLong("p"+i,penalty[i]).putBoolean("a"+i,active[i]).putBoolean("armed"+i,penaltyArmed[i]);if(team1!=null)e.putString("team1",team1.getText().toString()).putString("team2",team2.getText().toString()).putString("score1",score1.getText().toString()).putString("score2",score2.getText().toString()).putString("phone",phone.getText().toString());e.apply();}
 static int cue(long before,long after){long oldSeconds=(Math.max(0,before)+999)/1000,newSeconds=(Math.max(0,after)+999)/1000;if(oldSeconds>newSeconds&&newSeconds<=10)return newSeconds==0?2:1;return 0;}
 void advance(){long now=System.currentTimeMillis(),dt=Math.max(0,now-last),gameDt=running?Math.min(remain,dt):0,penDt=gameDt;int sound=0;if(running){long before=remain;remain=Math.max(0,remain-dt);sound=cue(before,remain);if(before>0&&remain==0)sound=3;}for(int i=0;i<4;i++)if(active[i]&&penaltyArmed[i]){long before=penalty[i];penalty[i]=Math.max(0,penalty[i]-penDt);sound=Math.max(sound,cue(before,penalty[i]));}if(remain==0)running=false;boolean anyPenalty=false;for(int i=0;i<4;i++)if(active[i]&&penaltyArmed[i]&&penalty[i]>0)anyPenalty=true;if(!anyPenalty)penaltyStarted=false;last=now;if(audible&&tones!=null&&dt<=1500&&sound>0)playCue(sound);}
 void playCue(int sound){if(sound==3){finishSoundUntil=System.currentTimeMillis()+2000;++soundGeneration;try{if(horn!=null)horn.release();horn=new android.media.MediaPlayer();android.content.res.AssetFileDescriptor fd=getAssets().openFd("horn.wav");horn.setDataSource(fd.getFileDescriptor(),fd.getStartOffset(),fd.getLength());fd.close();horn.setAudioStreamType(AudioManager.STREAM_MUSIC);horn.setVolume(1f,1f);horn.prepare();horn.start();}catch(Exception e){tones.startTone(ToneGenerator.TONE_CDMA_EMERGENCY_RINGBACK,1800);}return;}if(System.currentTimeMillis()<finishSoundUntil&&sound==2)return;if(sound==1){if(System.currentTimeMillis()>=finishSoundUntil)tones.startTone(ToneGenerator.TONE_PROP_BEEP,120);return;}finishSoundUntil=System.currentTimeMillis()+500;final int generation=++soundGeneration;for(int i=0;i<3;i++){handler.postDelayed(()->{if(audible&&tones!=null&&generation==soundGeneration)tones.startTone(ToneGenerator.TONE_PROP_BEEP,90);},i*160L);}}
 void change(Runnable r){advance();r.run();last=System.currentTimeMillis();render();save();}
 @Override protected void onResume(){super.onResume();audible=false;advance();render();if(tones==null){try{tones=new ToneGenerator(AudioManager.STREAM_MUSIC,100);}catch(RuntimeException e){Toast.makeText(this,"Countdown audio is unavailable on this device",Toast.LENGTH_LONG).show();}}setVolumeControlStream(AudioManager.STREAM_MUSIC);audible=true;handler.removeCallbacks(pulse);handler.post(pulse);}
 @Override protected void onPause(){audible=false;soundGeneration++;if(horn!=null){horn.release();horn=null;}advance();save();handler.removeCallbacks(pulse);if(tones!=null){tones.release();tones=null;}super.onPause();}
 String fmt(long n){long s=(Math.max(0,n)+999)/1000;return String.format(Locale.US,"%02d:%02d",s/60,s%60);}
 TextView text(String s,int size,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextSize(size);t.setTextColor(Color.BLACK);if(bold)t.setTypeface(null,Typeface.BOLD);t.setPadding(0,dp(4),0,dp(4));return t;}
 LinearLayout vertical(){LinearLayout l=new LinearLayout(this);l.setOrientation(1);return l;}
 LinearLayout row(){LinearLayout l=new LinearLayout(this);l.setOrientation(0);l.setGravity(Gravity.CENTER_VERTICAL);return l;}
 void weighted(LinearLayout l,View v){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,-2,1);p.setMargins(dp(3),dp(3),dp(3),dp(3));l.addView(v,p);}
 LinearLayout card(LinearLayout parent){LinearLayout l=vertical();l.setPadding(dp(14),dp(12),dp(14),dp(12));GradientDrawable g=new GradientDrawable();g.setColor(Color.BLACK);g.setCornerRadius(dp(16));l.setBackground(g);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,dp(6),0,dp(6));parent.addView(l,p);return l;}
 Button button(String label,Runnable action){Button b=new Button(this);b.setText(label);b.setAllCaps(false);b.setMinHeight(dp(48));b.setOnClickListener(v->action.run());return b;}
 EditText field(String key,String fallback,int input){EditText e=new EditText(this);e.setSingleLine(true);e.setText(prefs.getString(key,fallback));e.setInputType(input);e.setTextSize(18);e.setSelectAllOnFocus(true);return e;}
 String appVersion(){try{return getPackageManager().getPackageInfo(getPackageName(),0).versionName;}catch(Exception e){return "Unknown";}}
 void darkPanel(View view){if(view instanceof TextView){((TextView)view).setTextColor(Color.WHITE);if(view instanceof EditText)((EditText)view).setHintTextColor(Color.LTGRAY);}if(view instanceof Button){view.setBackgroundTintList(android.content.res.ColorStateList.valueOf(Color.rgb(45,45,45)));}if(view instanceof ViewGroup){ViewGroup group=(ViewGroup)view;for(int i=0;i<group.getChildCount();i++)darkPanel(group.getChildAt(i));}}
 interface NumberAction{void accept(int value);}
 void manualNumber(LinearLayout parent,String hint,int max,NumberAction apply){EditText input=new EditText(this);input.setHint(hint);input.setInputType(2);input.setSingleLine(true);input.setTextSize(16);input.setImeOptions(android.view.inputmethod.EditorInfo.IME_ACTION_DONE);parent.addView(input,new LinearLayout.LayoutParams(-1,-2));Runnable commit=()->{String value=input.getText().toString().trim();if(value.isEmpty())return;try{int n=Integer.parseInt(value);if(n<1||n>max)throw new NumberFormatException();change(()->apply.accept(n));}catch(NumberFormatException e){input.setError("Enter 1–"+max);}};input.setOnEditorActionListener((v,id,event)->{if(id==android.view.inputmethod.EditorInfo.IME_ACTION_DONE){commit.run();return true;}return false;});input.setOnFocusChangeListener((v,focus)->{if(!focus)commit.run();});}
 void manualPenalty(LinearLayout parent,int i){EditText input=new EditText(this);input.setHint("Custom m:ss");input.setSingleLine(true);input.setTextSize(16);input.setInputType(android.text.InputType.TYPE_CLASS_DATETIME|android.text.InputType.TYPE_DATETIME_VARIATION_TIME);input.setImeOptions(android.view.inputmethod.EditorInfo.IME_ACTION_DONE);parent.addView(input,new LinearLayout.LayoutParams(-1,-2));Runnable commit=()->{String value=input.getText().toString().trim();if(value.isEmpty())return;try{String[] parts=value.split(":",-1);if(parts.length!=2)throw new NumberFormatException();int m=Integer.parseInt(parts[0]),sec=Integer.parseInt(parts[1]);if(m<0||m>999||sec<0||sec>59||m*60+sec==0)throw new NumberFormatException();long duration=(m*60L+sec)*1000;change(()->{penalty[i]=duration;active[i]=true;penaltyArmed[i]=false;});}catch(NumberFormatException e){input.setError("Use m:ss, e.g. 1:30");}};input.setOnEditorActionListener((v,id,event)->{if(id==android.view.inputmethod.EditorInfo.IME_ACTION_DONE){commit.run();return true;}return false;});input.setOnFocusChangeListener((v,focus)->{if(!focus)commit.run();});}
 void build(){ScrollView scroll=new ScrollView(this);scroll.setFillViewport(true);scroll.setOnApplyWindowInsetsListener((v,insets)->{v.setPadding(insets.getSystemWindowInsetLeft(),insets.getSystemWindowInsetTop(),insets.getSystemWindowInsetRight(),insets.getSystemWindowInsetBottom());return insets;});LinearLayout root=vertical();root.setPadding(dp(14),dp(18),dp(14),dp(24));root.setBackgroundColor(Color.WHITE);scroll.addView(root);setContentView(scroll);
 ImageView brand=new ImageView(this);try(java.io.InputStream stream=getAssets().open("resolute.png")){brand.setImageDrawable(android.graphics.drawable.Drawable.createFromStream(stream,null));}catch(java.io.IOException e){}brand.setAdjustViewBounds(true);brand.setScaleType(ImageView.ScaleType.FIT_CENTER);brand.setContentDescription("Resolute Lacrosse");root.addView(brand,new LinearLayout.LayoutParams(-1,-2));TextView subtitle=text("sideline control",26,true);subtitle.setTypeface(Typeface.create("serif",Typeface.BOLD));subtitle.setGravity(Gravity.CENTER);root.addView(subtitle,new LinearLayout.LayoutParams(-1,-2));TextView version=text("Version "+appVersion(),12,false);version.setTextColor(Color.BLACK);root.addView(version);status=text("READY",12,true);status.setTextColor(Color.BLACK);root.addView(status);
 LinearLayout config=card(root);config.addView(text("GAME LENGTH · PERIODS",13,true));LinearLayout lengths=row();config.addView(lengths);for(int i=0;i<5;i++){final int n=i+1;periodChoices[i]=button(""+n,()->change(()->{periods=n;period=Math.min(period,periods);}));weighted(lengths,periodChoices[i]);}
 manualNumber(config,"Custom game length (periods)",99,n->{periods=n;period=Math.min(period,periods);});config.addView(text("GAME MINUTES · PER PERIOD",13,true));LinearLayout mins=row();config.addView(mins);int[] options={5,8,12,15};for(int i=0;i<4;i++){final int n=options[i];minuteChoices[i]=button(""+n,()->change(()->{minutes=n;remain=n*60000L;running=false;}));weighted(mins,minuteChoices[i]);}
 manualNumber(config,"Custom minutes per period",999,n->{minutes=n;remain=n*60000L;running=false;});toggle=new Switch(this);toggle.setText("RUNNING PENALTY");toggle.setChecked(rp);config.addView(toggle);config.addView(text("Penalties begin only with Start All Penalties",12,false));toggle.setOnCheckedChangeListener((b,on)->change(()->rp=on));
 LinearLayout main=card(root);periodLabel=text("PERIOD 1 / 4",32,true);periodLabel.setGravity(Gravity.CENTER);main.addView(periodLabel);game=text("08:00",76,true);game.setTypeface(Typeface.MONOSPACE,Typeface.BOLD);game.setGravity(Gravity.CENTER);main.addView(game);LinearLayout controls=row();main.addView(controls);start=button("▶ START",()->change(()->{if(!running&&remain==0)remain=minutes*60000L;running=!running;}));weighted(controls,start);weighted(controls,button("Reset",()->change(()->{running=false;remain=minutes*60000L;})));LinearLayout navigation=row();main.addView(navigation);prev=button("← Previous",()->move(-1));next=button("Next Period →",()->move(1));weighted(navigation,prev);weighted(navigation,next);
 root.addView(text("PENALTY MINUTES",16,true));mode=text("WAITING FOR START",12,false);root.addView(mode);allPenalties=button("▶ Start All Penalties",()->change(()->{boolean anyRunning=false;for(int j=0;j<4;j++)if(penaltyArmed[j]&&penalty[j]>0)anyRunning=true;penaltyStarted=!anyRunning;for(int j=0;j<4;j++)penaltyArmed[j]=penaltyStarted&&active[j]&&penalty[j]>0;}));root.addView(allPenalties);root.addView(text("Arm penalties here. Game Start/Pause controls all clocks.",12,false));
 for(int rowIndex=0;rowIndex<2;rowIndex++){LinearLayout line=row();root.addView(line);for(int col=0;col<2;col++){final int i=rowIndex*2+col;LinearLayout holder=vertical();weighted(line,holder);LinearLayout box=card(holder);box.addView(text("PENALTY "+(i+1),12,true));pClock[i]=text("00:00",34,true);pClock[i].setTypeface(Typeface.MONOSPACE,Typeface.BOLD);box.addView(pClock[i]);pState[i]=text("EMPTY",10,false);box.addView(pState[i]);LinearLayout timeRow=row();box.addView(timeRow,new LinearLayout.LayoutParams(-1,dp(48)));for(int sec:new int[]{30,60,120,180}){final long duration=sec*1000L;Button time=button(fmt(duration),()->change(()->{penalty[i]=duration;active[i]=true;penaltyArmed[i]=false;}));time.setMinWidth(0);time.setMinimumWidth(0);time.setPadding(0,0,0,0);time.setTextSize(11);time.setSingleLine(true);timeRow.addView(time,new LinearLayout.LayoutParams(0,dp(48),1));}Button addThirty=button("+30",()->change(()->{penalty[i]+=30000;active[i]=true;if(penalty[i]==30000)penaltyArmed[i]=false;}));box.addView(addThirty,new LinearLayout.LayoutParams(-1,dp(48)));Button clear=button("Clear",()->change(()->{penalty[i]=0;active[i]=false;penaltyArmed[i]=false;}));box.addView(clear,new LinearLayout.LayoutParams(-1,dp(48)));}}
 LinearLayout report=card(root);report.addView(text("FINAL SCORE REPORT",18,true));LinearLayout teams=row();report.addView(teams);LinearLayout t1=vertical(),t2=vertical();weighted(teams,t1);weighted(teams,t2);t1.addView(text("TEAM 1",12,true));t2.addView(text("TEAM 2",12,true));team1=field("team1","Team 1",1);team2=field("team2","Team 2",1);t1.addView(team1);t2.addView(team2);score1=field("score1","0",2);score2=field("score2","0",2);for(EditText e:new EditText[]{score1,score2}){e.setTextSize(48);e.setGravity(Gravity.CENTER);e.setFilters(new InputFilter[]{new InputFilter.LengthFilter(4)});}t1.addView(score1);t2.addView(score2);report.addView(text("TEXT MESSAGE NUMBER",13,true));phone=field("phone","",3);phone.setHint("Enter phone number");report.addView(phone);preview=text("",16,false);preview.setTextIsSelectable(true);report.addView(preview);report.addView(button("✉ SEND TEXT",()->send()));report.addView(text("Review and send in your messaging app.",12,false));
 TextWatcher watch=new TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int c,int f){}public void onTextChanged(CharSequence s,int a,int before,int count){preview.setText(message());save();}public void afterTextChanged(Editable e){}};for(EditText e:new EditText[]{team1,team2,score1,score2,phone})e.addTextChangedListener(watch);for(int i=0;i<root.getChildCount();i++){View section=root.getChildAt(i);if(section instanceof LinearLayout)darkPanel(section);}
 }
 void move(int delta){change(()->{period=Math.max(1,Math.min(periods,period+delta));running=false;remain=minutes*60000L;});}
 String name(EditText e,String fallback){String s=e.getText().toString().trim();return s.isEmpty()?fallback:s;}
 int score(EditText e){try{return Math.max(0,Integer.parseInt(e.getText().toString()));}catch(Exception x){return 0;}}
 String message(){return "Lacrosse Final Score\n"+name(team1,"Team 1")+": "+score(score1)+"\n"+name(team2,"Team 2")+": "+score(score2);}
 void send(){String number=phone.getText().toString().replaceAll("[\\s().-]","");if(!number.matches("\\+?[0-9]{7,15}")){phone.setError("Enter a valid phone number");phone.requestFocus();return;}Intent i=new Intent(Intent.ACTION_SENDTO,Uri.parse("smsto:"+number));i.putExtra("sms_body",message());try{startActivity(i);}catch(ActivityNotFoundException e){new AlertDialog.Builder(this).setMessage("No messaging app is available. Select and copy the score preview instead.").setPositiveButton("OK",null).show();}}
 void render(){if(game==null)return;boolean anyRunning=false;for(int j=0;j<4;j++)if(penaltyArmed[j]&&penalty[j]>0)anyRunning=true;allPenalties.setText(anyRunning?"Ⅱ Pause All Penalties":"▶ Start All Penalties");game.setText(fmt(remain));periodLabel.setText("PERIOD "+period+" / "+periods);status.setText(running?"● RUNNING":remain==0?"ENDED":"READY");start.setText(running?"Ⅱ PAUSE":"▶ START");prev.setEnabled(period>1);next.setEnabled(period<periods);mode.setText(penaltyStarted?"PENALTIES STARTED":rp?"RUNNING PENALTY":"WAITING FOR START");for(int i=0;i<5;i++)periodChoices[i].setTextColor(periods==i+1?green:Color.WHITE);int[] opts={5,8,12,15};for(int i=0;i<4;i++)minuteChoices[i].setTextColor(minutes==opts[i]?green:Color.WHITE);for(int i=0;i<4;i++){pClock[i].setText(fmt(penalty[i]));pClock[i].setTextColor(active[i]&&penalty[i]>0?Color.rgb(186,79,35):Color.WHITE);pState[i].setText(!active[i]?"EMPTY":penalty[i]==0?"COMPLETE":penaltyArmed[i]?(running?"COUNTING DOWN":"PAUSED BY MASTER"):"SET / WAITING");}preview.setText(message());}
}
